# Generated by Django 4.1.6 on 2023-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=50)),
                ('content_post', models.TextField()),
                ('photo_post', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('author_post', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo_sections', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Services', models.CharField(max_length=50)),
            ],
        ),
    ]
