# Generated by Django 4.1.6 on 2023-02-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0002_rename_name_sections_name_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Services', models.CharField(max_length=50)),
            ],
        ),
    ]
