# Generated by Django 4.1.6 on 2023-02-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0004_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_user1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('sons_cont', models.IntegerField()),
                ('man_cont', models.IntegerField()),
                ('girl_cont', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='login_user',
        ),
    ]
