# Generated by Django 4.1.6 on 2023-03-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0005_login_user1_delete_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('sons_cont', models.IntegerField(blank=True, null=True)),
                ('man_cont', models.IntegerField(blank=True, null=True)),
                ('girl_cont', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('اعزب', 'اعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('ارمل', 'ارمل')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='login_user1',
        ),
    ]
