# Generated by Django 4.1.6 on 2023-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0006_login_user_delete_login_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='id_user',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('اعزب', 'اعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق'), ('ارمل', 'ارمل')], max_length=10),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
