# Generated by Django 4.1.6 on 2023-03-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0007_alter_login_user_address_alter_login_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=50)),
                ('content_post', models.TextField()),
                ('photo_post', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('author_post', models.CharField(max_length=50)),
                ('date_post', models.DateField()),
            ],
        ),
    ]
