# Generated by Django 4.1.6 on 2023-03-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0009_login_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateField(null=True),
        ),
    ]
