# Generated by Django 4.1.6 on 2023-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0010_delete_posts_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
