# Generated by Django 4.1.6 on 2023-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0012_alter_login_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
