# Generated by Django 4.1.7 on 2023-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0014_alter_login_user_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_adress', models.CharField(max_length=50)),
                ('imag', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('subjact', models.TextField()),
                ('dep_name', models.CharField(max_length=50)),
                ('Thread_header', models.TextField()),
                ('the_topic', models.TextField()),
                ('the_topic_imag', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('dep_name2', models.CharField(max_length=50)),
                ('Thread_header2', models.TextField()),
                ('the_topic2', models.TextField()),
                ('the_topic_imag2', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
