# Generated by Django 4.1.7 on 2023-03-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0016_remove_department_dep_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag2',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag3',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag4',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag5',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
    ]
