# Generated by Django 4.1.7 on 2023-03-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0017_alter_department_imag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_imag',
            field=models.ImageField(blank=True, null=True, upload_to='department'),
        ),
    ]
