# Generated by Django 4.2 on 2023-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0018_department_dep_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
