# Generated by Django 4.2 on 2023-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0019_accountform'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_adress', models.CharField(max_length=50)),
                ('imag', models.ImageField(blank=True, null=True, upload_to='service')),
                ('subjact', models.TextField(blank=True, null=True)),
                ('dep_name', models.CharField(max_length=50)),
                ('dep_imag', models.ImageField(blank=True, null=True, upload_to='service')),
                ('Thread_header', models.TextField(blank=True, null=True)),
                ('the_topic', models.TextField(blank=True, null=True)),
                ('the_topic_imag', models.ImageField(blank=True, null=True, upload_to='service')),
                ('Thread_header2', models.TextField(blank=True, null=True)),
                ('the_topic2', models.TextField(blank=True, null=True)),
                ('the_topic_imag2', models.ImageField(blank=True, null=True, upload_to='service')),
                ('Thread_header3', models.TextField(blank=True, null=True)),
                ('the_topic3', models.TextField(blank=True, null=True)),
                ('the_topic_imag3', models.ImageField(blank=True, null=True, upload_to='service')),
                ('Thread_header4', models.TextField(blank=True, null=True)),
                ('the_topic4', models.TextField(blank=True, null=True)),
                ('the_topic_imag4', models.ImageField(blank=True, null=True, upload_to='service')),
                ('Thread_header5', models.TextField(blank=True, null=True)),
                ('the_topic5', models.TextField(blank=True, null=True)),
                ('the_topic_imag5', models.ImageField(blank=True, null=True, upload_to='service')),
            ],
        ),
    ]
