# Generated by Django 4.2 on 2023-04-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0020_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
