# Generated by Django 4.2 on 2023-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0022_home_list_services_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='services_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Services', models.CharField(max_length=50)),
            ],
        ),
    ]
