# Generated by Django 4.2 on 2023-04-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0023_services_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_list',
        ),
    ]
