# Generated by Django 4.2 on 2023-04-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0024_delete_home_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services_list',
            new_name='sss',
        ),
        migrations.RenameField(
            model_name='services_detail',
            old_name='dep_adress',
            new_name='name_Services',
        ),
        migrations.RemoveField(
            model_name='services_detail',
            name='imag',
        ),
        migrations.RemoveField(
            model_name='services_detail',
            name='subjact',
        ),
    ]
