# Generated by Django 4.2 on 2023-04-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0025_rename_services_list_sss_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
