# Generated by Django 4.2 on 2023-04-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0026_delete_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sss',
        ),
    ]
