# Generated by Django 4.2 on 2023-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0028_rename_services_detail_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_imag',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag2',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag3',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag4',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='department',
            name='the_topic_imag5',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
