# Generated by Django 4.2 on 2023-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0003_rename_id_user_loginuser_nationalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='NationalId',
            new_name='National_Id',
        ),
    ]
