# Generated by Django 4.2 on 2023-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0005_rename_national_id_loginuser_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='NationalId',
            field=models.IntegerField(default=int, unique=True),
        ),
    ]
