# Generated by Django 4.2 on 2023-04-24 19:12

from django.db import migrations, models
import utils.genrate_code


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0009_loginuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='code',
            field=models.CharField(default=utils.genrate_code.genrate_code, max_length=10),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
