# Generated by Django 4.2 on 2023-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0010_loginuser_active_loginuser_code_loginuser_code_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='password1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='password2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
