# Generated by Django 4.2 on 2023-04-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0011_loginuser_password1_loginuser_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='NationalId',
            field=models.CharField(default=int, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='address',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
