# Generated by Django 4.2 on 2023-04-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0012_alter_loginuser_nationalid_alter_loginuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='loginuser',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='sons',
            old_name='user',
            new_name='username',
        ),
    ]
