# Generated by Django 4.2 on 2023-04-25 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logina', '0013_rename_user_girl_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girl_users', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='sons',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sons_users', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
