# Generated by Django 4.2 on 2023-04-25 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logina', '0014_alter_girl_username_alter_sons_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='username',
        ),
        migrations.RemoveField(
            model_name='sons',
            name='username',
        ),
        migrations.AddField(
            model_name='girl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='girl_users', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='sons',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sons_users', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='NationalId',
            field=models.CharField(default=int, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
