# Generated by Django 4.1 on 2023-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0019_alter_profile_user_myprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='NationalId',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='myProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
