# Generated by Django 4.1 on 2023-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0021_alter_loginuser_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='password2',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('1', 'أعزب'), ('2', 'متزوج'), ('3', 'مطلق'), ('4', 'أرمل')], max_length=20, null=True),
        ),
    ]
