# Generated by Django 4.2 on 2023-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0022_remove_loginuser_email_remove_loginuser_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='age',
            new_name='age_sons',
        ),
        migrations.RenameField(
            model_name='girl',
            old_name='name',
            new_name='name_sons',
        ),
        migrations.RenameField(
            model_name='girl',
            old_name='national_id',
            new_name='national_id_sons',
        ),
    ]
