# Generated by Django 4.1 on 2023-05-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0023_rename_age_girl_age_sons_rename_name_girl_name_sons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='age_sons',
            new_name='age_girls',
        ),
        migrations.RenameField(
            model_name='girl',
            old_name='name_sons',
            new_name='name_girls',
        ),
        migrations.RenameField(
            model_name='girl',
            old_name='national_id_sons',
            new_name='national_id_girls',
        ),
        migrations.RenameField(
            model_name='sons',
            old_name='age',
            new_name='age_sons',
        ),
        migrations.RenameField(
            model_name='sons',
            old_name='name',
            new_name='name_sons',
        ),
        migrations.RenameField(
            model_name='sons',
            old_name='national_id',
            new_name='national_id_sons',
        ),
    ]
