# Generated by Django 4.2 on 2023-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0024_rename_age_sons_girl_age_girls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
