# Generated by Django 4.2.2 on 2023-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0029_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'الادمن'), ('doctor', 'دكتور'), ('patient', 'مريض')], default='patient', max_length=20, null=True),
        ),
    ]
