# Generated by Django 4.2 on 2023-06-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0030_loginuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chronic_diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_level', models.CharField(blank=True, choices=[('natural', 'طبيعي'), ('low', 'منخفض'), ('high', 'مرتفع')], max_length=20, null=True)),
                ('sugar_level', models.CharField(blank=True, choices=[('natural', 'طبيعي'), ('low', 'منخفض'), ('high', 'مرتفع')], max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('o+', 'o+'), ('a+', 'a+'), ('b+', 'b+'), ('ab+', 'ab+'), ('o-', 'o-'), ('a-', 'a-'), ('b-', 'b-'), ('ab-', 'ab-')], max_length=20, null=True)),
                ('Genetic_diseases', models.CharField(blank=True, max_length=20, null=True)),
                ('chronic_diseases', models.CharField(blank=True, max_length=20, null=True)),
                ('Drugs', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='conjunctivitis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='esoteric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctors_note', models.CharField(blank=True, max_length=20, null=True)),
                ('pharmaceutical', models.CharField(blank=True, max_length=20, null=True)),
                ('the_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
