# Generated by Django 4.2 on 2023-06-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logina', '0031_analyzes_chronic_diseases_conjunctivitis_esoteric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinations',
            old_name='Doctors_note',
            new_name='doctors_note',
        ),
        migrations.AlterField(
            model_name='vaccinations',
            name='the_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
